### ISSUE TITLE
Bug: V15.0.0 Not Working on ownCloud 8.2.1

### ISSUE THREAD

**Issue by kneiser** [interfasys/galleryplus#41]
I just upgraded to this version on my Raspberry Pi Raspbian (a.k.a Debian 8) LAMP server. PHP Version 5.6.17-0+deb8u1 is installed. I also tried this on a Fedora 23 LAMP server, PHP Version 5.6.19 installed.

In both O/S cases I use Apache 2.4 and MariaDB.

I installed all the prerequisites: php5-imagick, imagemagick, and php.ini "extension=imagick.so"
**config/config.php:**
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    11 => 'OC\\Preview\\Illustrator',
    12 => 'OC\\Preview\\Postscript',
    13 => 'OC\\Preview\\Photoshop',
    14 => 'OC\\Preview\\TIFF'
  ),

When I use the application I get a Gallery+ page as blank, no ownCloud file scan wheel appears. 

ownCloud Logreader states error:
**Error	PHP	Module 'imagick' already loaded at Unknown#0**
If I comment out the php.ini extension line the error does not occur but the application page is still blank.

Do command-line: **sudo -u apache php occ files:scan --all**
**PHP Warning:  Module 'imagick' already loaded in Unknown on line 0**

The previous version worked fine. Did I miss anything?

**Comment by aronovgj** [comment]
Same issue on 8.2.3, Nginx, PHP 5.6.19, MySQL, Mint 17.3

**Comment by aronovgj** [comment]
Version 14.4.0 works again after I changed exactly nothing.

**Comment by aronovgj** [comment]
Ok solved it - for me at least. If you use fastcgi_cache, clear your server cache.

**Comment by dirkpape** [comment]
I have the same problem while using server version 8.2.3 or 9.0.1RC. When upgrading to Version 15 of galleryplus I always see an empty screen, when I switch to the gallery view. No spinning wheel, no image appearing even after waiting long time.

**Comment by dirkpape** [comment]
ok. I carefully read the readme from the gallery+ v15 again and disabled the app files_move. After that gallery+ works fine.

**Comment by rhatguy** [comment]
Add another user with no images on gallery+ v15.  Luckily I found this thread and noticed dirkpape's comment about the files_move app.  That is definitely the culprit for me also.  After disabling files_move, gallery+ is working again.

gallery+ should fail with a message similar to how it fails when the gallery app is enabled.  At least then when you see the failure you know what the problem is.  Currently the blank screen leaves users to wonder why things aren't working.

**Comment by aronovgj** [comment]
> gallery+ should fail with a message similar to how it fails when the gallery app is enabled.

Please don't make it fail on purpose.

I'd consider it merely a warning because I have files_move and gallery+ enabled and for me both work without issues after clearing cache.
Still  8.2.3, Nginx, PHP 5.6.19, MySQL, Mint 17.3, Redis, fastcgi_cache

**Comment by rhatguy** [comment]
aronovgj Can you specify which cache you are clearing to make the two apps work together?  I tried flushing everything on the browser side and they still don't work together.  I'm assuming its something on the server side?

**Comment by aronovgj** [comment]
As described here
https://github.com/owncloud/documentation/wiki/NGINX-Configuration

I'm using caching in Nginx, compiled into it. That's the one I cleaned.

**Comment by oparoz** [comment]
I somehow missed that report...

It seems files_move is only a problem on 9.0 and we can't block it as we can't test all apps.
The first thing to do when an app fails loading is to disable experimental apps. The developer has not bothered to submit his or her app for approval, so expect issues down the line.

@kneiser - Since Gallery doesn't install or need imagick, I suspect a packaging problem

**Comment by oparoz** [comment]
Closing since the issues are not caused by Gallery+
